# Generated by Django 5.1.4 on 2026-01-07 21:28

import asociaciones_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField(unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Año",
                "verbose_name_plural": "Años",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="Asociacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.SlugField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                (
                    "anio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asociaciones",
                        to="asociaciones_app.anio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asociación",
                "verbose_name_plural": "Asociaciones",
                "ordering": ["anio", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="AsociacionUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol_en_asociacion", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "asociacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="asociaciones_app.asociacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_asociacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de usuario",
                "verbose_name_plural": "Asignaciones de usuarios",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ExpedienteCAIMUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institucion", models.CharField(blank=True, max_length=255)),
                ("representante_legal", models.CharField(blank=True, max_length=255)),
                ("obs_general", models.TextField(blank=True)),
                ("recomendaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("observacion_admin", models.TextField(blank=True)),
                ("aprobado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedientes_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedientes_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asociacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expediente_caimus",
                        to="asociaciones_app.asociacion",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedientes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente CAIMUS",
                "verbose_name_plural": "Expedientes CAIMUS",
            },
        ),
        migrations.CreateModel(
            name="ExpedienteEstadoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                ("cambiado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cambiado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="asociaciones_app.expedientecaimus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de estado",
                "verbose_name_plural": "Historial de estados",
                "ordering": ["-cambiado_en"],
            },
        ),
        migrations.CreateModel(
            name="ItemChecklistCAIMUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("seccion", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=255)),
                ("hint", models.TextField(blank=True)),
                ("entregado", models.BooleanField(default=False)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="caimus/%Y/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            asociaciones_app.models.validate_pdf_size,
                        ],
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="asociaciones_app.expedientecaimus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item checklist CAIMUS",
                "verbose_name_plural": "Items checklist CAIMUS",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="ResolucionExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correlativo", models.CharField(max_length=30, unique=True)),
                ("fecha_emision", models.DateField()),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="resoluciones/%Y/"
                    ),
                ),
                ("contenido_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolucion",
                        to="asociaciones_app.expedientecaimus",
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolución",
                "verbose_name_plural": "Resoluciones",
            },
        ),
        migrations.AddConstraint(
            model_name="asociacion",
            constraint=models.UniqueConstraint(
                fields=("anio", "codigo"), name="unique_asociacion_codigo_por_anio"
            ),
        ),
        migrations.AddConstraint(
            model_name="asociacionusuario",
            constraint=models.UniqueConstraint(
                fields=("asociacion", "usuario"), name="unique_usuario_asociacion"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemchecklistcaimus",
            constraint=models.UniqueConstraint(
                fields=("expediente", "numero"), name="unique_item_por_expediente"
            ),
        ),
    ]
