# Generated by Django 5.1.4 on 2026-01-12 16:06

import asociaciones_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0002_itemchecklist_seccion_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemchecklistcaimus",
            name="seccion",
            field=models.PositiveIntegerField(
                choices=[(1, "Sección 1"), (2, "Sección 2"), (3, "Sección 3")],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="InformeMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="informes/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            asociaciones_app.models.validate_pdf_size,
                        ],
                    ),
                ),
                ("observaciones_usuario", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("observacion_admin", models.TextField(blank=True)),
                ("aprobado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="informes_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="informes_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asociacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes_mensuales",
                        to="asociaciones_app.asociacion",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="informes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe mensual",
                "verbose_name_plural": "Informes mensuales",
                "ordering": ["mes"],
            },
        ),
        migrations.CreateModel(
            name="InformeEstadoHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                ("cambiado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cambiado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="asociaciones_app.informemensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de estado de informe",
                "verbose_name_plural": "Historial de estados de informes",
                "ordering": ["-cambiado_en"],
            },
        ),
        migrations.AddConstraint(
            model_name="informemensual",
            constraint=models.UniqueConstraint(
                fields=("asociacion", "mes"), name="unique_informe_mes_asociacion"
            ),
        ),
    ]
