# Generated by Django 5.1.4 on 2026-04-09 18:27

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_CHECKLIST_ITEMS = [
    (1, "Solicitud dirigida al señor Ministro de Gobernación"),
    (2, "Plan Operativo Anual -POA-"),
    (3, "Copia legalizada del Testimonio de la Escritura Pública Constitutiva de la entidad"),
    (4, "Constancia de inscripción y actualización de datos -RTU-"),
    (5, "Solvencia Fiscal vigente"),
    (6, "Constancia de Inventario de Cuentas emitida por el Ministerio de Finanzas Públicas."),
    (7, "Certificación de la constancia de inscripción de la entidad en el Registro de Personas Jurídicas -REPEJU-"),
    (8, "Copia legalizada -DPI- de representante legal"),
    (9, "Copia legalizada del Acta Notarial de nombramiento de representante legal"),
    (10, "Constancia de inscripción y actualización de datos -RTU- del representante legal"),
    (11, "Solvencia Fiscal vigente, del Representante Legal"),
    (12, "Certificación de la constancia de inscripción en el Registro de Personas Jurídicas -REPEJU-"),
]


def poblar_checklist_por_anio(apps, schema_editor):
    Anio = apps.get_model("asociaciones_app", "Anio")
    ChecklistAnioItem = apps.get_model("asociaciones_app", "ChecklistAnioItem")
    Expediente = apps.get_model("asociaciones_app", "ExpedienteCAIMUS")
    ItemChecklist = apps.get_model("asociaciones_app", "ItemChecklistCAIMUS")

    for anio in Anio.objects.all():
        if not ChecklistAnioItem.objects.filter(anio=anio).exists():
            ChecklistAnioItem.objects.bulk_create(
                [
                    ChecklistAnioItem(
                        anio=anio,
                        numero=numero,
                        titulo=titulo,
                        descripcion="",
                        activo=True,
                    )
                    for numero, titulo in DEFAULT_CHECKLIST_ITEMS
                ]
            )

        plantilla_por_numero = {
            item.numero: item
            for item in ChecklistAnioItem.objects.filter(anio=anio)
        }
        for expediente in Expediente.objects.filter(asociacion__anio=anio):
            for item in ItemChecklist.objects.filter(expediente=expediente):
                plantilla = plantilla_por_numero.get(item.numero)
                if plantilla and item.plantilla_item_id is None:
                    item.plantilla_item_id = plantilla.id
                    item.save(update_fields=["plantilla_item"])


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0004_actualizar_items_checklist_caimus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistAnioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "anio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="asociaciones_app.anio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item checklist por año",
                "verbose_name_plural": "Items checklist por año",
                "ordering": ["numero"],
            },
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="plantilla_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_expediente",
                to="asociaciones_app.checklistanioitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklistanioitem",
            constraint=models.UniqueConstraint(
                fields=("anio", "numero"), name="unique_checklist_anio_numero"
            ),
        ),
        migrations.RunPython(poblar_checklist_por_anio, migrations.RunPython.noop),
    ]
