# Generated by Django 5.1.4 on 2026-04-09 20:47

import asociaciones_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_pdf_legacy_a_narrativo(apps, schema_editor):
    InformeMensual = apps.get_model("asociaciones_app", "InformeMensual")
    for informe in InformeMensual.objects.exclude(pdf="").exclude(pdf__isnull=True):
        if not informe.archivo_narrativo:
            informe.archivo_narrativo = informe.pdf
            informe.save(update_fields=["archivo_narrativo"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "asociaciones_app",
            "0005_checklistanioitem_itemchecklistcaimus_plantilla_item_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="informemensual",
            name="archivo_narrativo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="informes/narrativos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    asociaciones_app.models.validate_pdf_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="informemensual",
            name="archivo_presupuestario",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="informes/presupuestarios/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    asociaciones_app.models.validate_pdf_size,
                ],
            ),
        ),
        migrations.CreateModel(
            name="ResolucionInformeMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correlativo", models.CharField(max_length=50, unique=True)),
                ("fecha_emision", models.DateField()),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="resoluciones_informes/%Y/"
                    ),
                ),
                ("contenido_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "informe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolucion",
                        to="asociaciones_app.informemensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolución de informe mensual",
                "verbose_name_plural": "Resoluciones de informes mensuales",
            },
        ),
        migrations.RunPython(migrar_pdf_legacy_a_narrativo, migrations.RunPython.noop),
    ]
