# Generated by Django 5.1.4 on 2026-04-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0006_informemensual_archivo_narrativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
