# Generated by Django 5.1.4 on 2026-04-13 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0009_notificacionadmin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaRevisionAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("expediente", "Expediente"), ("informe", "Informe")],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("atendida", "Atendida")],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensaje", models.TextField()),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("atendida_en", models.DateTimeField(blank=True, null=True)),
                ("enlace", models.CharField(blank=True, max_length=255)),
                (
                    "asociacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas_revision",
                        to="asociaciones_app.asociacion",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entradas_revision_admin_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas_revision",
                        to="asociaciones_app.expedientecaimus",
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas_revision",
                        to="asociaciones_app.informemensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de revisión admin",
                "verbose_name_plural": "Entradas de revisión admin",
                "ordering": ["-creada_en"],
            },
        ),
    ]
