# Generated by Django 5.1.4 on 2026-04-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0010_entradarevisionadmin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_caimus_aprobados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="estado_item",
            field=models.CharField(
                choices=[
                    ("borrador", "Pendiente"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                ],
                default="borrador",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="fecha_aprobacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="fecha_rechazo",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="observacion_revision",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="rechazado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_caimus_rechazados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
