# Generated by Django 5.1.4 on 2026-04-30 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0011_itemchecklistcaimus_aprobado_por_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionInformeAnio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ]
                    ),
                ),
                ("requerido", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuraciones_informe_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "anio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_informes",
                        to="asociaciones_app.anio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de informe por año",
                "verbose_name_plural": "Configuraciones de informes por año",
                "ordering": ["mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anio", "mes"),
                        name="unique_configuracion_informe_anio_mes",
                    )
                ],
            },
        ),
    ]
