# Generated by Django 5.1.4 on 2026-04-30 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0012_configuracioninformeanio"),
    ]

    operations = [
        migrations.AddField(
            model_name="informemensual",
            name="archivo_presupuestario_excel",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="informes/presupuestario_excel/%Y/%m/",
                validators=[django.core.validators.FileExtensionValidator(["xlsx"])],
            ),
        ),
    ]
