# Generated by Django 5.1.4 on 2026-05-20 18:32

import asociaciones_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0013_informemensual_archivo_presupuestario_excel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemchecklistcaimus",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="caimus/%Y/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "xls", "xlsx"]
                    ),
                    asociaciones_app.models.validate_pdf_size,
                ],
            ),
        ),
    ]
