# Generated by Django 5.1.4 on 2026-05-21 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0014_alter_itemchecklistcaimus_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="fecha_carga",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="itemchecklistcaimus",
            name="subido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_caimus_subidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
