# Generated by Django 5.1.4 on 2026-05-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0015_itemchecklistcaimus_fecha_actualizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asociacion",
            name="acuerdo_gubernativo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="asociacion",
            name="dpi_representante_legal",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="asociacion",
            name="nombre_representante_legal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
