# Generated by Django 5.1.4 on 2026-05-26 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0016_asociacion_acuerdo_gubernativo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialItemExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("ARCHIVO_SUBIDO", "Archivo subido"),
                            ("ARCHIVO_ACTUALIZADO", "Archivo actualizado"),
                            ("OBSERVACION_ADMIN", "Observación de revisión"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("EN_REVISION", "En revisión"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="expedientes/historial/%Y/"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="asociaciones_app.itemchecklistcaimus",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de ítem de expediente",
                "verbose_name_plural": "Historial de ítems de expediente",
                "ordering": ["creado_en"],
            },
        ),
    ]
