# Generated by Django 5.1.4 on 2026-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0017_historialitemexpediente"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmaConstancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("profesion", models.CharField(blank=True, max_length=100, null=True)),
                ("cargo", models.CharField(max_length=255)),
                ("departamento", models.CharField(max_length=255)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Firma de constancia",
                "verbose_name_plural": "Firmas de constancia",
                "ordering": ["orden", "nombre"],
            },
        ),
    ]
