# Generated by Django 5.1.4 on 2026-06-30 16:48

import asociaciones_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0018_firmaconstancia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartamentoConstancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Departamento de constancia",
                "verbose_name_plural": "Departamentos de constancia",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="firmaconstancia",
            name="firma_png",
            field=models.ImageField(
                blank=True,
                help_text="Firma en formato PNG",
                null=True,
                upload_to="firmas_constancia/",
                validators=[
                    django.core.validators.FileExtensionValidator(["png"]),
                    asociaciones_app.models.validate_png_size,
                ],
            ),
        ),
        migrations.CreateModel(
            name="RevisorConstancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisores",
                        to="asociaciones_app.departamentoconstancia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisor_constancia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisor de constancia",
                "verbose_name_plural": "Revisores de constancia",
                "ordering": ["departamento__orden", "orden", "usuario__first_name"],
                "unique_together": {("departamento", "usuario")},
            },
        ),
    ]
