# Generated by Django 5.1.4 on 2026-08-26 17:41

import asociaciones_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "asociaciones_app",
            "0019_departamentoconstancia_firmaconstancia_firma_png_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asociacion",
            name="convenio_firmado",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="asociaciones/convenios/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    asociaciones_app.models.validate_pdf_size,
                    asociaciones_app.models.validate_pdf_content,
                ],
            ),
        ),
    ]
