# Generated by Django 5.1.4 on 2026-08-26 18:15

import asociaciones_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0020_asociacion_convenio_firmado"),
    ]

    operations = [
        migrations.AddField(
            model_name="anio",
            name="acuerdo_gubernativo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos_legales/acuerdos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    asociaciones_app.models.validate_pdf_size,
                    asociaciones_app.models.validate_pdf_content,
                ],
            ),
        ),
        migrations.AddField(
            model_name="anio",
            name="decreto_congreso",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos_legales/decretos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    asociaciones_app.models.validate_pdf_size,
                    asociaciones_app.models.validate_pdf_content,
                ],
            ),
        ),
    ]
