# Generated by Django 5.1.4 on 2026-09-08 15:22

import asociaciones_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0022_departamento_asociacion_departamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="asociacion",
            name="es_caimus",
            field=models.BooleanField(default=True, verbose_name="Asociación CAIMUS"),
        ),
        migrations.AddField(
            model_name="informemensual",
            name="archivo_conaprevi",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="informes/conaprevi/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    asociaciones_app.models.validate_pdf_size,
                    asociaciones_app.models.validate_pdf_content,
                ],
            ),
        ),
    ]
