# Generated by Django 5.1.4 on 2026-10-01 20:37

import asociaciones_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asociaciones_app", "0023_asociacion_es_caimus_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RespuestaAdministrativaInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=asociaciones_app.models.respuesta_administrativa_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            asociaciones_app.models.validate_pdf_size,
                            asociaciones_app.models.validate_pdf_content,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("vigente", models.BooleanField(default=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            (
                                "RESPUESTA_ADMIN_SUBIDA",
                                "Respuesta administrativa cargada",
                            ),
                            (
                                "RESPUESTA_ADMIN_ACTUALIZADA",
                                "Respuesta administrativa actualizada",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_administrativas",
                        to="asociaciones_app.informemensual",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="respuestas_administrativas_informes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta administrativa de informe",
                "verbose_name_plural": "Respuestas administrativas de informes",
                "ordering": ["-version", "-creado_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("informe", "version"),
                        name="unique_respuesta_admin_version_informe",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("vigente", True)),
                        fields=("informe",),
                        name="unique_respuesta_admin_vigente_informe",
                    ),
                ],
            },
        ),
    ]
