from django.urls import path

from . import views

app_name = "asociaciones"

urlpatterns = [
    path("", views.asociaciones_inicio, name="inicio"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/resumen/excel/", views.exportar_resumen_asociaciones_excel, name="exportar_resumen_asociaciones_excel"),
    path("anios/", views.anio_list, name="anios_list"),
    path("anios/nuevo/", views.anio_create, name="anio_create"),
    path("anios/<int:pk>/editar/", views.anio_edit, name="anio_edit"),
    path("anios/<int:pk>/checklist/", views.anio_checklist, name="anio_checklist"),
    path("anios/<int:pk>/informes-config/", views.anio_informes_config, name="anio_informes_config"),
    path("anios/<int:pk>/checklist/guardar/", views.anio_checklist_guardar, name="anio_checklist_guardar"),
    path("<int:anio_id>/lista/", views.asociacion_list, name="asociacion_list"),
    path("<int:anio_id>/nuevo/", views.asociacion_create, name="asociacion_create"),
    path("<int:pk>/editar/", views.asociacion_edit, name="asociacion_edit"),
    path("<int:pk>/usuarios/", views.asociacion_usuarios, name="asociacion_usuarios"),
    path("mis-asociaciones/", views.mis_asociaciones, name="mis_asociaciones"),
    path(
        "<int:asociacion_id>/notificaciones/marcar-leidas/",
        views.notificaciones_marcar_leidas,
        name="notificaciones_marcar_leidas",
    ),
    path("<int:pk>/caimus/", views.expediente_caimus, name="expediente_caimus"),
    path("<int:pk>/caimus/enviar-revision/", views.expediente_enviar_revision, name="expediente_enviar_revision"),
    path("<int:pk>/caimus/sincronizar-checklist/", views.expediente_sync_checklist, name="expediente_sync_checklist"),
    path("<int:pk>/informes/", views.informes_mensuales, name="informes_mensuales"),
    path("expedientes/<int:pk>/revision/", views.expediente_revision, name="expediente_revision"),
    path("expedientes/<int:pk>/resolucion/pdf/", views.resolucion_pdf, name="resolucion_pdf"),
    path("constancias/validar/<path:codigo>/", views.validar_constancia_expediente, name="validar_constancia_expediente"),
    path(
        "expedientes/<int:expediente_id>/items/<int:item_id>/upload/",
        views.item_upload,
        name="item_upload",
    ),
    path(
        "expedientes/<int:expediente_id>/items/<int:item_id>/observacion/",
        views.item_observacion,
        name="item_observacion",
    ),
    path(
        "expedientes/<int:expediente_id>/items/<int:item_id>/revision/",
        views.item_revision_estado,
        name="item_revision_estado",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/upload/",
        views.informe_upload,
        name="informe_upload",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/upload/narrativo/",
        views.informe_upload_narrativo,
        name="informe_upload_narrativo",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/upload/presupuestario/",
        views.informe_upload_presupuestario,
        name="informe_upload_presupuestario",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/upload/presupuestario-excel/",
        views.informe_upload_presupuestario_excel,
        name="informe_upload_presupuestario_excel",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/observacion/",
        views.informe_observacion,
        name="informe_observacion",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/enviar-revision/",
        views.informe_enviar_revision,
        name="informe_enviar_revision",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/estado/",
        views.informe_estado,
        name="informe_estado",
    ),
    path(
        "<int:asociacion_id>/informes/<int:mes>/resolucion/pdf/",
        views.informe_resolucion_pdf,
        name="informe_resolucion_pdf",
    ),
    path("bandeja-revision/", views.bandeja_revision, name="bandeja_revision"),
    path("bandeja-revision/<int:pk>/atender/", views.bandeja_marcar_atendida, name="bandeja_marcar_atendida"),
    path("alertas-admin/<int:pk>/revisar/", views.alerta_admin_revisar, name="alerta_admin_revisar"),
    path("asignaciones/", views.asignaciones_list, name="asignaciones_list"),
    path("configuracion/firmas-constancia/", views.firmas_constancia_list, name="firmas_constancia_list"),
    path("configuracion/firmas-constancia/crear/", views.firma_constancia_create, name="firma_constancia_create"),
    path("configuracion/firmas-constancia/<int:pk>/editar/", views.firma_constancia_update, name="firma_constancia_update"),
    path("configuracion/firmas-constancia/<int:pk>/estado/", views.firma_constancia_toggle, name="firma_constancia_toggle"),
    path("configuracion/departamentos-constancia/", views.departamentos_constancia_list, name="departamentos_constancia_list"),
    path("configuracion/departamentos-constancia/crear/", views.departamento_constancia_create, name="departamento_constancia_create"),
    path("configuracion/departamentos-constancia/<int:pk>/editar/", views.departamento_constancia_update, name="departamento_constancia_update"),
    path("configuracion/departamentos-constancia/<int:pk>/estado/", views.departamento_constancia_toggle, name="departamento_constancia_toggle"),
    path("configuracion/revisores-constancia/", views.revisores_constancia_list, name="revisores_constancia_list"),
    path("configuracion/revisores-constancia/crear/", views.revisor_constancia_create, name="revisor_constancia_create"),
    path("configuracion/revisores-constancia/<int:pk>/editar/", views.revisor_constancia_update, name="revisor_constancia_update"),
    path("configuracion/revisores-constancia/<int:pk>/estado/", views.revisor_constancia_toggle, name="revisor_constancia_toggle"),
]
