# Generated by Django 5.1.4 on 2025-02-26 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='almacen_app.ingreso'),
        ),
    ]
