# Generated by Django 5.1.4 on 2025-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0002_remove_asignacion_usuario_asignacion_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
