# Generated by Django 5.1.4 on 2025-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0004_frasemotivacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50)),
                ('numero_inicial', models.PositiveIntegerField()),
                ('numero_final', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
