# Generated by Django 5.1.4 on 2025-03-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0005_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen_app.serie'),
        ),
    ]
