# Generated by Django 5.1.4 on 2025-03-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0006_ingreso_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='numero_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
