# Generated by Django 5.1.4 on 2025-03-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0008_ingreso_numero_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='cantidad_renglon',
            new_name='renglon',
        ),
    ]
