# Generated by Django 5.1.4 on 2025-03-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0009_rename_cantidad_renglon_ingreso_renglon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stock',
        ),
        migrations.CreateModel(
            name='form1h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('renglon', models.PositiveIntegerField()),
                ('orden_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('nit_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('precio_total_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero_serie', models.PositiveIntegerField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form1h', to='almacen_app.articulo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen_app.proveedor')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen_app.serie')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_linea', models.PositiveIntegerField(unique=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura', to='almacen_app.articulo')),
                ('form1h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen_app.form1h')),
            ],
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='almacen_app.form1h'),
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
