# Generated by Django 5.1.4 on 2025-03-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0010_remove_articulo_codigo_remove_articulo_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1h',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='form1h',
            name='precio_total_ingreso',
        ),
        migrations.RemoveField(
            model_name='form1h',
            name='precio_unitario',
        ),
    ]
