# Generated by Django 5.1.4 on 2025-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0011_remove_form1h_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1h',
            name='cantidad',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form1h',
            name='precio_total_ingreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='form1h',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
