# Generated by Django 5.1.4 on 2025-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0013_dependencia_programa_remove_form1h_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1h',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
