# Generated by Django 5.1.4 on 2025-04-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0014_alter_form1h_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorDetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
