# Generated by Django 5.1.4 on 2025-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0015_contadordetallefactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_linea', models.IntegerField(unique=True)),
            ],
        ),
    ]
