# Generated by Django 5.1.4 on 2025-05-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0016_linealibre'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaReservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.IntegerField(unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('form1h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.form1h')),
            ],
        ),
    ]
