# Generated by Django 5.1.4 on 2025-05-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0017_lineareservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='id_linea',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.UniqueConstraint(fields=('form1h', 'id_linea'), name='unique_linea_per_form1h'),
        ),
    ]
