# Generated by Django 5.1.4 on 2025-05-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0019_form1h_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AsignacionDetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen_app.departamento')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='almacen_app.detallefactura')),
            ],
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
