# Generated by Django 5.1.4 on 2025-05-28 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0020_articulo_activo_departamento_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaciondetallefactura',
            name='detalle',
        ),
        migrations.AddField(
            model_name='asignaciondetallefactura',
            name='articulo',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='almacen_app.articulo'),
            preserve_default=False,
        ),
    ]
