# Generated by Django 5.1.4 on 2025-06-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0022_usuariodepartamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardex',
            options={'ordering': ['fecha', 'id']},
        ),
        migrations.AddField(
            model_name='kardex',
            name='fuente_asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen_app.asignaciondetallefactura'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='fuente_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen_app.detallefactura'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='saldo_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kardex',
            name='saldo_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
