# Generated by Django 5.1.4 on 2025-06-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0025_requerimiento_detallerequerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
