# Generated by Django 5.1.4 on 2025-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0026_detallerequerimiento_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('despachado', 'Despachado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado')], default='pendiente', max_length=20),
        ),
    ]
