# Generated by Django 5.1.4 on 2025-07-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0027_alter_requerimiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('despachado', 'Despachado')], default='pendiente', max_length=20),
        ),
    ]
