# Generated by Django 5.1.4 on 2025-07-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0030_requerimiento_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='motivo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
