# Generated by Django 5.1.4 on 2025-08-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0031_alter_requerimiento_motivo_historialtransferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='requiere_vencimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
