# Generated by Django 5.1.4 on 2025-08-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0031_alter_requerimiento_motivo'),
        ('almacen_app', '0031_alter_requerimiento_motivo_historialtransferencia'),
    ]

    operations = [
    ]
