# Generated by Django 5.1.4 on 2025-08-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0032_articulo_requiere_vencimiento_and_more'),
        ('almacen_app', '0032_merge_20250805_1230'),
    ]

    operations = [
    ]
