# Generated by Django 5.1.4 on 2025-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0032_articulo_requiere_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1h',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
    ]
