# Generated by Django 5.1.4 on 2025-08-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0033_alter_form1h_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimiento',
            name='cantidad_despachada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
