# Generated by Django 5.1.4 on 2025-08-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0034_detallerequerimiento_cantidad_despachada'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='motivo_rechazo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
