# Generated by Django 5.1.4 on 2025-08-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0033_merge_20250806_1224'),
        ('almacen_app', '0035_requerimiento_motivo_rechazo'),
    ]

    operations = [
    ]
