# Generated by Django 5.1.4 on 2025-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0035_requerimiento_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1h',
            name='folio_inventario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='form1h',
            name='nomenclatura',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
