# Generated by Django 5.1.4 on 2025-08-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0036_form1h_folio_inventario_form1h_nomenclatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1h',
            name='folio_inventario',
        ),
        migrations.RemoveField(
            model_name='form1h',
            name='nomenclatura',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='folio_inventario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='nomenclatura',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
