# Generated by Django 5.1.4 on 2025-08-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0037_remove_form1h_folio_inventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='requiere_inventario_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InventarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_inventario', models.CharField(max_length=30)),
                ('nomenclatura', models.CharField(max_length=10)),
                ('detalle_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='almacen_app.detallefactura')),
            ],
        ),
    ]
