# Generated by Django 5.1.4 on 2025-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0038_articulo_requiere_inventario_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallerequerimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('despachado', 'Despachado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('despachado', 'Despachado'), ('rechazado', 'Rechazado'), ('parcial', 'Parcial'), ('enviado', 'Enviado')], default='pendiente', max_length=20),
        ),
    ]
