# Generated by Django 5.1.4 on 2025-08-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0036_merge_20250814_1448'),
        ('almacen_app', '0039_alter_detallerequerimiento_estado_and_more'),
    ]

    operations = [
    ]
