# Generated by Django 5.1.4 on 2025-09-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0041_alter_articulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
