# Generated by Django 5.1.4 on 2025-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0042_alter_detallefactura_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
