# Generated by Django 5.1.4 on 2025-09-16 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0043_alter_detallefactura_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='fuente_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen_app.detallerequerimiento', unique=True),
        ),
    ]
